### ISSUE TITLE
Complete fibonacci.c program

### ISSUE THREAD

**Issue by campionfellin** [OpenGuide/C-Guide-for-Beginners#9]
You should be able to find the file in https://github.com/OpenGuide/C-Guide-for-Beginners/tree/master/CalculatorFunctions

**Comment by simmsb** [comment]
Alright if I take this?

**Comment by hrishikeshathalye** [comment]
I would like to contribute to this by adding code for fibonacci using recursion. Can I take this?

**Comment by ewan-mcjesus** [comment]
i would like to contribute this project

**Comment by saru-d2** [comment]
i would like to contribute to this project

**Comment by shivanshu1303** [comment]
I would like to contribute to this project for my first PR . Please.

**Comment by khandelwalsarvesh** [comment]
Being a good programmer I believe I can write the Fibonacci program. Give me chance so that I can contribute
